- accepted/rfc-process.md
As the Bytecode Alliance grows, we need more formalized ways of communicating about and reaching consensus on major changes to core projects. This document proposes to adapt ideas from Rust’s [RFC](https://github.com/rust-lang/rfcs/) and [MCP](https://forge.rust-lang.org/compiler/mcp.html) processes to the Bytecode Alliance context.
[Rendered proposal text](https://github.com/aturon/ba-rfcs/blob/rfc-process/accepted/rfc-process.md)
> RFC process proposal

- accepted/async-imports.md
This RFC proposes adding native support to the `wasmtime` crate for
imported functions which are `async`. Additionally it provides APIs to
call wasm functions as an `async` function.
[rendered](https://github.com/alexcrichton/rfcs-2/blob/async-wasmtime/accepted/async-imports.md)
> RFC: Add `async` support to wasmtime

- accepted/wasmtime-instance-allocator.md
[Rendered RFC](https://github.com/peterhuene/rfcs/blob/instance-pools/accepted/wasmtime-instance-allocator.md)
This RFC proposes adding an "instance allocator" abstraction to Wasmtime to
allow for alternative instance resource allocation strategies.
One such strategy will be a "pooling instance allocator" that can quickly
allocate instances, memories, and tables from the host address space that has
been reserved in advance.
This RFC is inspired by a Lucet performance feature called "regions".
> RFC: Add instance allocator support to Wasmtime.

- accepted/benchmark-infrastructure.md
This RFC proposes establishing a benchmarking infrastructure for Cranelift/wasmtime.
[rendered](https://github.com/bytecodealliance/rfcs/blob/0e241326310062717e34c3a097b5f8bef26a020c/accepted/benchmark-infrastructure.md)
> RFC: benchmarking infrastructure.

- accepted/shared-host-functions.md
[Rendered RFC](https://github.com/peterhuene/rfcs/blob/engine-host-functions/accepted/shared-host-functions.md)
This RFC proposes to extend the Wasmtime API to allow users to define host
functions in a `Config` that can be shared between multiple engines and
therefore stores.
Today, `Func` is used to define host functions, but it is tied to a `Store`.
If users desire short-lived stores to ensure short-lived instances, host
functions need to be redefined upon every module instantiation.
By defining host functions with a `Config`, instances can be created
without having to redefine the host functions; this will make for faster module
instantiations in scenarios where a module is repeatedly instantiated.
> RFC: shared host functions. 

- accepted/cranelift-backend-transition.md
[Rendered](https://github.com/cfallin/rfcs/blob/cranelift-backend-transition/accepted/cranelift-backend-transition.md)
This RFC proposes to switch the default Cranelift compiler backend for the `cranelift-codegen` crate (i.e., use of Cranelift as a library) and for Wasmtime from the old x86-64 backend to the new x86-64 backend. Details on how we should decide, what steps we should take to build confidence, ensure backwards compatibility, and gradually switch over are proposed.
> RFC: Transition Cranelift and Wasmtime to new x86-64 backend by default.

- accepted/new-api.md
[Rendered](https://github.com/alexcrichton/rfcs-2/blob/new-api/accepted/new-api.md)
---
Overhaul the `wasmtime` crate's API to improve it along a number of vectors:
* Greatly improve the multithreading story in all languages (Rust, C, Go, ...),
namely enabling safe usage of `wasmtime` in multithreaded server runtimes
where wasm objects can migrate between threads.
* Leverage mutability in Rust to allow `&mut` access to user-defined state
instead of requiring users to use interior mutability.
* Simplify memory management in the C API and embeddings.
The only major cost relative to today's API is that `ExternRef` will move to
atomic reference counting and will require `T: Send + Sync` on constructors.
> RFC: Redesign Wasmtime's API

- accepted/wasmtime-one-dot-oh.md
This RFC is a proposal to release Wasmtime with a 1.0 version. In doing so this
proposal also defines what it means to be 1.0 and details areas such as:
* What is Wasmtime's stability story.
* What will Wasmtime's release process be.
* What users can expect from Wasmtime going forward.
[Rendered](https://github.com/bytecodealliance/rfcs/blob/1d8ee8e2ef21d3a15317245cc5863bce29199361/accepted/wasmtime-one-dot-oh.md)
> RFC: Wasmtime 1.0

- accepted/remove-old-cranelift-backend.md
[Rendered](https://github.com/cfallin/rfcs/blob/remove-old-backend/accepted/remove-old-cranelift-backend.md)
This RFC describes the process by which we hope to remove the old Cranelift x86 backend, with the appropriate consensus beforehand and the appropriate cleanups afterward.
It has been spurred by @bjorn3's work to draft the technical work of actually snipping it out in bytecodealliance/wasmtime#3009 (thanks!).
> RFC to remove old Cranelift x86 backend.

- accepted/cranelift-roadmap-2022.md
[Markdown rendered](https://github.com/cfallin/rfcs/blob/cranelift-2022/accepted/cranelift-roadmap-2022.md)
This is a roadmap for work on Cranelift in 2022, highlighting areas of interest and outlining the major projects that we want to focus on in the next year. It is meant to be part guiding document, part aspirational collection of interesting ideas and possibilities. As with [last year's roadmap](https://github.com/bytecodealliance/rfcs/pull/8), we likely won't accomplish all of it, though if we're fortunate we may achieve a good amount of it.
Thanks to @fitzgen for feedback on a draft, and many others (see Acknowledgments at end) for general input on these topics.
Apologies if this misses anything important -- I tried to be as comprehensive as possible, while still coalescing into …
> Cranelift Roadmap for 2022

- accepted/cfi-improvements-with-pauth-and-bti.md
This RFC proposes to improve control flow integrity for compiled WebAssembly code by utilizing two technologies from the Arm instruction set architecture - Pointer Authentication and Branch Target Identification.
[Rendered](https://github.com/akirilov-arm/rfcs/blob/cfi_improvements/accepted/cfi-improvements-with-pauth-and-bti.md)
> RFC: CFI Improvements with PAuth and BTI

- accepted/isle-extended-patterns.md
[Rendered](https://github.com/cfallin/rfcs/blob/isle-extended-patterns/accepted/isle-extended-patterns.md)
This RFC proposes an extension to the ISLE pattern-matching DSL used by Cranelift's code generation
backends. The extension is a backward-compatible proposal that is meant to make certain lowering
patterns easier to express. The ideas are informed by our experience so far with the DSL, and aim
to replace some awkward uses of extractors with in-arguments with clearer, more direct idioms
using a new language form.
cc @abrown @fitzgen @jlb6740 @akirilov-arm @sparker-arm @uweigand
> Cranelift/ISLE: allow extended left-hand-side patterns for clearer lowering rules

- accepted/cranelift-dynamic-vector.md
- cranelift-sizeless-vector.md
Copyright (c) 2021, Arm Limited.
> RFC: Cranelift sizeless vector types

- README.md
At some point the template for "complete" appears to have been renamed to "full" but the README reference to it was not updated.
> Fix link to full RFC template

- accepted/benchmark-suite.md
The link to the paper _A Workload Characterization of the SPEC CPU2017 Benchmark Suite_  does not go to the paper anymore, but goes to one of the author's (Tosiron Adegbija) [website](https://tosiron.com/). I changed the link to a new valid link which is from the same author's website and contains the paper.
> fixed link for spec CPU2017 paper

- accepted/vulnerability-response-runbook.md
This RFC proposes the vulnerability response process used by the Bytecode Alliance. It is structured as a runbook: a set of steps to be followed by the team responding to a discovered vulnerability.
It documents the process we followed for several different security advisories in Wasmtime and Lucet, for example:
https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-88xq-w8cq-xfg7
https://github.com/bytecodealliance/lucet/security/advisories/GHSA-hf79-8hjp-rrvq
> RFC: Vulnerability response runbook

- accepted/wasmtime-baseline-compilation.md
[Rendered](https://github.com/saulecabrera/rfcs/blob/wasmtime-baseline-compilation/accepted/wasmtime-baseline-compilation.md)
This RFC proposes the addition of a new WebAssembly (Wasm) compiler to Wasmtime:
a single-pass or “baseline” compiler. A baseline compiler works to improve
overall compilation performance, yielding faster startup times, at the cost of
less optimized code.
This RFC describes:
* The motivation for a baseline compiler
* A high-level overview and description of the structure of the baseline
compiler
* A high-level overview of its integration with Wasmtime
cc @cfallin @fitzgen @alexcrichton @bnjbvr
> RFC: Baseline compilation in Wasmtime

- accepted/cranelift-roadmap-2023.md
[rendered](https://github.com/cfallin/rfcs/blob/cranelift-2023/accepted/cranelift-roadmap-2023.md)
This RFC proposes a roadmap for Cranelift in 2023. Like [last year's roadmap](https://github.com/bytecodealliance/rfcs/pull/18), it covers a wide range of projects: from ongoing work that follows from last year's projects and completes or extends them, to work in the immediate future that we know how to do and know we need to do, to an array of more speculative ideas and topics that we think would be interesting.
The goal of this RFC is to come to some general sort of agreement that these are interesting topics, and to gather any other such topics from the community. Nothing here binds us to complete these ideas, though of course, we hope to achieve a good number of them in due time. (In …
> Cranelift Roadmap for 2023

- accepted/what-is-considered-a-security-bug.md
> Wasmtime has documented processes for reporting, responding to, patching, and disclosing security vulnerabilities. However, the Wasmtime project does not currently define which kinds of bugs are and are not considered security vulnerabilities. This RFC aims to reach consensus on that definition.
> New RFC: What is vs. is not considered a security bug in Wasmtime?

- accepted/wasmtime-debugging.md
> Implement guest debugging capabilities in Wasmtime and integrate those abilities with surrounding debugging toolchains.
Co-authored-by: Nick Fitzgerald - @fitzgen 
Co-authored-by: Rainy Sinclair - @itsrainy
> Debugging support in Wasmtime

- accepted/wasmtime-lts.md
This is borne out of discussion on bytecodealliance/wasmtime#10074 and bytecodealliance/wasmtime#10161 and proposes adding an LTS channel for Wasmtime. The general tl;dr; is:
* Wasmtime LTS releases will be every 10th release, or 10 months apart.
* LTS releases are supported for 20 months.
* LTS releases are guaranteed to receive security fixes, and may optionally receive bug fixes. Feature backports are not supported, even if they're provided.
[Rendered](https://github.com/alexcrichton/rfcs-2/blob/wasmtime-lts/accepted/wasmtime-lts.md)
> Add an LTS channel of release for Wasmtime

- accepted/exception-handling.md
This RFC proposes to implement the [exception handling](https://github.com/WebAssembly/exception-handling) proposal in Wasmtime. At the time of writing, exception handling is a phase 4 proposal.
I think there are lots of details worth discussing about possible designs and strategies on how to realise them. I am hoping that this document can be used to seed those discussions here.
I would like to give credit to @fitzgen for guidance on how to put this RFC together as well as helping with developing the ideas, thanks!
> Implementing the exception handling proposal in Wasmtime
